new: type inference, upgrading to ESmodule and cleaning up
bgrnwd/fotmob pull request #434
Opened 2023-12-08 03:15 UTC by ItamarShDev

### Description

In this PR, I have made the following changes:
1. Upgraded the ts file to ES6 and target to node.
2. The API will return JSON and throw an error on failure, to be compatible with best practices.
3. Added type inference for the api calls. if the conversion fails - the api returns a JSON object
4. cleaned up the code to handle errors easier
### Checklist

- [x] Code compiles correctly
- [x] Created tests which fail without the change (if applicable)
- [x] All lint and unit tests passing
- [x] Extended the README / documentation, if necessary

### Additional Comments

Anything else you'd like to add.

2023-12-10 03:29 UTC, bgrnwd commented
@ItamarShDev Thanks for the PR, give me a couple days to look it over.

2023-12-11 12:21 UTC, ItamarShDev commented
> @ItamarShDev Thanks for the PR, give me a couple days to look it over.

Thanks!

2023-12-16 19:38 UTC, bgrnwd requested changes

2023-12-16 19:38 UTC, bgrnwd commented on package.json
>    "version": "1.1.0",
Mind bumping this to `2.0.0`?

2023-12-16 19:38 UTC, bgrnwd commented on test/fotmob.test.ts
Would you mind adding some additional test cases to make sure the new types are working correctly?

2023-12-17 14:20 UTC, ItamarShDev commented on package.json
> -  "name": "fotmob",
Mistake, adding back

2023-12-17 14:20 UTC, ItamarShDev commented on package.json
>    "version": "1.1.0",
done

2023-12-18 00:54 UTC, ItamarShDev commented on test/fotmob.test.ts
Added

2023-12-21 03:16 UTC, bgrnwd approved these changes
Thanks for the contribution! I'll get this merged in and a new release out there shortly

2023-12-21 03:17 UTC, merged

2023-12-23 09:16 UTC, ItamarShDev commented
> Thanks for the contribution! I'll get this merged in and a new release out there shortly

Thanks! patiently waiting for the version :)

2023-12-24 04:59 UTC, bgrnwd commented
It should be out there now!