Added transfers endpoint
bgrnwd/fotmob pull request #443
Opened 2024-01-15 23:07 UTC by jamtur01

### Description

Added the transfers endpoint.

### Checklist

- [X] Code compiles correctly
- [X] Created tests which fail without the change (if applicable)
- [X] All lint and unit tests passing
- [X] Extended the README / documentation, if necessary

2024-01-16 03:10 UTC, bgrnwd approved these changes

2024-01-16 03:14 UTC, bgrnwd commented
@jamtur01 Thanks for the PR!

2024-01-16 04:11 UTC, jamtur01 commented
@bgrnwd Done - I also added another endpoint to return all leagues. Happy to pull it out too.

2024-01-17 01:30 UTC, bgrnwd requested changes

2024-01-17 01:30 UTC, bgrnwd commented on docs/api.md
> +<https://www.fotmob.com/api/transfer>
```suggestion
<https://www.fotmob.com/api/worldnews>
```

2024-01-17 01:30 UTC, bgrnwd commented on package.json
> +  "version": "2.2.2",
My bad, I should have been more explicit. I think this should be `2.3.0`

2024-01-17 01:32 UTC, bgrnwd commented
> @bgrnwd Done - I also added another endpoint to return all leagues. Happy to pull it out too.

Nope, happy to have it. Just reviewed the PR and suggested a couple minor changes.

2024-01-17 18:25 UTC, ItamarShDev commented
Just pointing out that is seems the fomatter settings of the OP is changing all files.
We need to make sure the formating is consistent

2024-01-18 04:32 UTC, bgrnwd commented
> Just pointing out that is seems the fomatter settings of the OP is changing all files. We need to make sure the formating is consistent

I did notice that. I was hoping the `.prettierrc` and `.eslintrc.json` would help with that but I did see your additional linting changes in your most recent PR. I think those will be good to add.

2024-01-18 04:50 UTC, bgrnwd approved these changes

2024-01-18 04:50 UTC, merged